# Generated by Django 4.0.3 on 2022-04-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date', '-pub_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-likes'], 'verbose_name': '菜品'},
        ),
    ]
