# Generated by Django 4.0.3 on 2022-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_comment_options_alter_meal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar', null=True, upload_to='user_avatar/', verbose_name='头像'),
        ),
    ]
