# Generated by Django 4.0.3 on 2022-04-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-likes'], 'verbose_name': '菜品', 'verbose_name_plural': '菜品'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '评论'},
        ),
    ]
