# Generated by Django 4.0.3 on 2022-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='picture',
            field=models.ImageField(default='default_meal_picture.jpg', upload_to='meal_picture/'),
        ),
    ]
