# Generated by Django 4.0.3 on 2022-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_likemeal_likecomment_dislikemeal_collectmeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
