# Generated by Django 4.0.3 on 2022-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/default0.jpg', null=True, upload_to='user_avatar/', verbose_name='头像'),
        ),
    ]
